### ISSUE TITLE
Adding valid code leads to compilation fail

### ISSUE THREAD

**Issue by 0152la** [mc-imperial/shader-compiler-bugs#57] opened 2016-12-16 16:27 UTC
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/NVIDIA-770-WebGL-ANGLE/compile_fail/large-v100-webgl-110c72abeb4815aa_inv_variant_33) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/NVIDIA-770-WebGL-ANGLE/compile_fail/large-v100-webgl-110c72abeb4815aa_inv_variant_33)

What is interesting in the compilation error message is the following line:

`ERROR: 0:76: 'webgl_360c969568c90722' : redefinition`

This leads to believe that there is an issue with some renaming of variables happening on the low level. Tested with Chrome and Firefox on Windows 10, verified with glslangValidator. Also ran via OpenGL and it successfully compiles and renders.

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/NVIDIA-770-WebGL-ANGLE/compile_fail/large-v100-webgl-110c72abeb4815aa_inv_variant_33/original.png "recipient image")

Variant:

[Compilation output](https://github.com/mc-imperial/shader-compiler-bugs/blob/master/NVIDIA-770-WebGL-ANGLE/compile_fail/large-v100-webgl-110c72abeb4815aa_inv_variant_33/variant.txt)

**Comment by paulthomson** [comment] 2016-12-20 23:13
I can repro this on my MacBook Pro (Intel) Windows 10 Chrome. But not on Edge. I guess this is an ANGLE bug. We should report to them.

**Comment by afd** [comment] 2016-12-21 07:04
I have the same issue on my Dell (Intel) laptop with Windows 10 Firefox, but not on Edge.  So agreed that this could be an ANGLE issue.

**Comment by 0152la** [comment] 2017-03-08 14:34
Updated drivers to 378.66 and retested. The shader is now correctly rendered in Chrome, but not in Firefox. Firefox issues the same "redefinition" error as observed above.

**Comment by paulthomson** [comment] 2017-03-08 14:50
Perhaps we should label this as an angle issue and maybe even remove the NVIDIA label? I assume Chrome has updated and that's why the issue is gone.

**Comment by 0152la** [comment] 2017-03-08 14:51
I agree on doing that for both this and #58. They seem to be related.

**Comment by afd** [comment] 2017-03-22 15:53
Closing as it indeed seems this issue has been fixed in ANGLE.

**Closed as completed by afd** 2017-03-22 15:53 UTC
Labels: compile-error, angle, could-not-reproduce
