### ISSUE TITLE
Adding a single, meaningless if-else to a shader source leads to different image

### ISSUE THREAD

**Issue by hevrard** [mc-imperial/shader-compiler-bugs#62] opened 2017-03-21 15:03 UTC
[[Shaders, screenshots, error log, reproduction steps, platform info, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/stable20-v100-all-transforms_33468.1_inv_variant_6) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/stable20-v100-all-transforms_33468.1_inv_variant_6)

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/stable20-v100-all-transforms_33468.1_inv_variant_6/original.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/AMD-R9-Tonga-285-380-Mesa-Linux/wrong_images/stable20-v100-all-transforms_33468.1_inv_variant_6/variant.png "variant image")

**Comment by hevrard** [comment] 2017-03-21 15:08
Reported to Mesa: https://bugs.freedesktop.org/show_bug.cgi?id=100303

**Comment by afd** [comment] 2017-07-19 15:26
The issue is reported to be fixed by Mesa folks.

**Closed as completed by afd** 2017-07-19 15:26 UTC
Labels: bad-image, amd-r9-tonga-285-380-mesa-linux, fix-deployed
