### ISSUE TITLE
Unreachable return statements cause some garbage to be rendered

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#48] opened 2016-12-14 15:36 UTC
[[Shaders, screenshots, error log, reproduction steps, platform info etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/nexus-player/wrong_images/large-v100-0f417c9b0a03750c_inv_variant_27) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/nexus-player/wrong_images/large-v100-0f417c9b0a03750c_inv_variant_27)

WebGL links for easy reproduction:

* [Recipient](http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/nexus-player/wrong_images/large-v100-0f417c9b0a03750c_inv_variant_27/webgl_viewer_recipient.html)
* [Variant](http://htmlpreview.github.io/?https://github.com/mc-imperial/shader-compiler-bugs/blob/master/nexus-player/wrong_images/large-v100-0f417c9b0a03750c_inv_variant_27/webgl_viewer_variant.html)

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/nexus-player/wrong_images/large-v100-0f417c9b0a03750c_inv_variant_27/recipient_reduced_final.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/nexus-player/wrong_images/large-v100-0f417c9b0a03750c_inv_variant_27/variant_27_reduced_final.png "variant image")

**Comment by paulthomson** [comment] 2016-12-14 15:51
Reported:
https://community.imgtec.com/forums/topic/bug-glsl-nexus-player-unreachable-return-statements-cause-garbage/

**Comment by paulthomson** [comment] 2016-12-20 18:04
ImgTech say they could not reproduce on their newer, internal drivers.

**Comment by afd** [comment] 2017-07-18 22:07
Imagination told us they could not reproduce this issue, so I am closing it and considering it "independently fixed."

**Closed as completed by afd** 2017-07-18 22:07 UTC
Labels: nexus-player, could-not-reproduce, potential-information-leak

**Comment by paulthomson** [comment] 2017-07-19 15:11
This bug STILL MANIFESTS on the latest Nexus Player update.
